@startuml

' 配置
package "Configuration" #DDD {
  class BaseInfo {
    String name
    String logoUrl
  }

  ' 课程种类
  class courseType {
    String id
    String name
    String employeeId
    TimeStamp createTime
    Number status
  }

  ' 课程素材
  class Material {
    String id
    String name
    String teacherEmployeeId ' 所属老师
    String employeeId
    TimeStamp createTime
    Number status
  }

  ' 课程要点
  class Essential {
    String id
    String name
    String level ' 要点级别
    String content ' 要点内容
    Number classHours ' 参考课时
    String employeeId
    TimeStamp createTime
    Number status
  }

  ' 难度等级
  class DifficultyLevel {
    String id
    String name
    String employeeId
    TimeStamp createTime
    Number status
  }

  ' 乐器类型
  class InstrumentType {
    String id
    String name
    String employeeId
    TimeStamp createTime
    Number status
  }

  ' 乐器使用情况
  class InstrumentUse {
    String id
    String name
    String employeeId
    TimeStamp createTime
    Number status
  }

  ' 学员等级
  class StudentLevel {
    String id
    String name
    String employeeId
    TimeStamp createTime
    Number status
  }

  ' 教师等级
  class TeacherLevel {
    String id
    String name
    String employeeId
    TimeStamp createTime
    Number status
  }

  ' 课程等级
  class CourseLevel {
    String id
    String name
    String employeeId
    TimeStamp createTime
    Number status
  }

  ' 客户来源
  class CustomerSource {
    String id
    String name
    String employeeId
    TimeStamp createTime
    Number status
  }

}

' 小程序配置
package "MiniProgram" {
  ' 轮播图
  class Banner {
    String id
    String name
    String imageUrl
    String linkUrl
    String employeeId
    TimeStamp createTime
    Number sort
  }

  ' 文章
  class Article {
    String id
    String title
    String subtitle
    String content
    Number isTop
    Number visibleType ' 可见类型
    String author
    String employeeId
    TimeStamp createTime
    Number sort
  }

  ' 协议
  class Agreement {
    String id
    String title
    String content
    String employeeId
    TimeStamp createTime
  }

  ' 关于我们
  class About {
    String id
    String title
    String content
    String employeeId
    TimeStamp createTime
  }
}


@enduml
