import Vue from "vue";
import {
  Button,
  Popover,
  ButtonGroup,
  Radio,
  Dialog,
  Tree,
  Tabs,
  TabPane,
  Collapse,
  CollapseItem,
  ColorPicker,
  Select,
  Option,
  Form,
  DatePicker,
  Upload,
  InputNumber,
  Switch,
  Table,
  TableColumn,
  Menu,
  Input,
  MenuItem,
  Card,
  Carousel,
  CarouselItem,
  Checkbox,
  CheckboxGroup,
  FormItem
} from "element-ui";

Vue.use(Table);
Vue.use(TableColumn);
Vue.use(Button);
Vue.use(Popover);
Vue.use(ButtonGroup);
Vue.use(Radio);
Vue.use(Dialog);
Vue.use(Tree);
Vue.use(Tabs);
Vue.use(TabPane);
Vue.use(Collapse);
Vue.use(CollapseItem);
Vue.use(ColorPicker);
Vue.use(Select);
Vue.use(Option);
Vue.use(Form);
Vue.use(FormItem);
Vue.use(DatePicker);
Vue.use(Upload);
Vue.use(InputNumber);
Vue.use(Menu);
Vue.use(MenuItem);
Vue.use(Input);
Vue.use(Card);
Vue.use(Carousel);
Vue.use(CarouselItem);
Vue.use(Switch);
Vue.use(Checkbox);
Vue.use(CheckboxGroup);
